apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitork8spod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitork8spod
  template:
    metadata:
      labels:
        app: monitork8spod
    spec:
      serviceAccount: worker
      containers:
        - name: container-monitork8spod
          image: fspelling/monitor-k8s-pod:v4
          envFrom:
            - configMapRef:
                name: monitork8spod