apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: boardsk8s
spec:
  ingressClassName: nginx
  rules:
    - host: [host-name]
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: boardsk8s
                port: 
                  number: 80
